call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()

set tabstop=4 softtabstop=4 shiftwidth=4
set expandtab
set number ruler
set autoindent smartindent
syntax enable

